### ISSUE TITLE
music-metadata

### ISSUE THREAD

**Issue by Borewit** [zinovik/node-audio-collection#1]
I think you should give [music-metadata](https://www.npmjs.com/package/music-metadata) to read metadata. Promise based and TypeScript definitions build in. It supports any common audio format.

**Comment by zinovik** [comment]
Thank you! I will check it.

**Comment by zinovik** [comment]
@Borewit 
It works like a charm!

**Comment by Borewit** [comment]
Glad you like! If getting the duration is a requirement, you can use:

```js
const options = { duration: true };
```
It will parse the entire file, if that is, what is required to calculate the duration.

**Comment by zinovik** [comment]
Yeah, I am going to use music-metadata module instead of mp3-duration module to get the file duration ;)

**Comment by zinovik** [comment]
It works much faster! And one less module ;)
